#ifndef _WIN_USER_SETTINGS_H_
#define _WIN_USER_SETTINGS_H_

#define WOLFSSL_HAVE_MIN
#define WOLFSSL_HAVE_MAX
#define WOLFSSL_DES_ECB

#define WC_RSA_BLINDING
#define NO_MULTIBYTE_PRINT

#define OPENSSL_EXTRA
#define WOLFSSL_RIPEMD
#define NO_PSK
#define HAVE_EXTENDED_MASTER
#define WOLFSSL_SNIFFER
#define HAVE_SECURE_RENEGOTIATION

#define HAVE_AESGCM
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512

#define HAVE_SUPPORTED_CURVES
#define HAVE_TLS_EXTENSIONS

#define HAVE_ECC
#define ECC_SHAMIR
#define ECC_TIMING_RESISTANT

#endif /* _WIN_USER_SETTINGS_H_ */
